name: growthx
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1

  # Local Database
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4

  # Charts
  fl_chart: ^0.71.0

  # =========================
  # Backend Integration
  # =========================

  # HTTP Client
  dio: ^5.8.0+1

  # JWT Secure Storage
  flutter_secure_storage: ^9.2.2

  # File Picker (Document Upload / RAG)
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf